### ISSUE TITLE
error installing dependencies

### ISSUE THREAD

**Issue by pbellec** [main-educational/brain_decoding#2]
I get the following error running  `pip install -r binder/requirements.txt`

Looking in links: https://download.pytorch.org/whl/torch_stable.html, https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
Collecting nilearn==0.8.0
  Using cached nilearn-0.8.0-py3-none-any.whl (4.9 MB)
Collecting pandas==0.25.1
  Downloading pandas-0.25.1.tar.gz (12.6 MB)
     |████████████████████████████████| 12.6 MB 13.8 MB/s 
Collecting psutil==5.8.0
  Downloading psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
     |████████████████████████████████| 296 kB 42.8 MB/s 
Collecting torch==1.8.1+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp38-cp38-linux_x86_64.whl (169.1 MB)
     |████████████████████████████████| 169.1 MB 21 kB/s 
Collecting torchvision==0.9.1
  Downloading https://download.pytorch.org/whl/cu111/torchvision-0.9.1%2Bcu111-cp38-cp38-linux_x86_64.whl (17.6 MB)
     |████████████████████████████████| 17.6 MB 4.0 MB/s 
Collecting torch-cluster
  Downloading https://data.pyg.org/whl/torch-1.8.0%2Bcpu/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl (411 kB)
     |████████████████████████████████| 411 kB 772 kB/s 
Collecting torch-scatter
  Downloading torch_scatter-2.0.9.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/pbellec/env/fmri_decoding/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8_y2m8tz/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8_y2m8tz/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8_y2m8tz/torch-scatter/pip-egg-info
         cwd: /tmp/pip-install-8_y2m8tz/torch-scatter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8_y2m8tz/torch-scatter/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pbellec** [comment]
seems to be resolved on my home computer. Not sure what the issue was. Closing for now.

**Comment by htwangtw** [comment]
I ran into the issue on compute canada as well
Supported version on compute canada is newer than the requirement file specified:

- Keras 2.7.0
- tensorflow 2.7.0
- torch==1.8.1 (instead of 1.8.1+cpu)

I can update the requirements and test for the build

**Comment by htwangtw** [comment]
I have temporarily fixed it again by bumping things to 1.11.0, but the inconsistency in environment setup is a real pain.
Will consider dockerise things....
